--- 
- 
  become: true
  hosts: all
  name: "Deploy Java program"
  tasks: 
    - 
      name: "Installation de docker"
      register: result_install
      shell: "amazon-linux-extras install docker && systemctl start docker"
    - 
      debug: var=result_install
    - 
      file: 
        mode: 511
        owner: ec2-user
        path: /app
        state: directory
      name: "Création du dossier /app sur la machine distante"
    - 
      copy: 
        dest: /app
        mode: 420
        src: helloWorld.class
      name: "Copier (faire un scp) le fichier local helloWorld.class sur le dossier remote /app"
    - 
      copy: 
        dest: /app
        mode: 420
        src: Dockerfile
      name: "Copier (faire un scp) le fichier local Dockerfile sur le dossier remote /app"
    - 
      name: "On genere l'image docker, on l'appelle formation/java:1.0"
      register: result
      shell: "cd /app && docker build -t formation/java:1.0 ."
    - 
      debug: var=result
    - 
      name: "On execute le contenur de l'image docker formation/java:1.0"
      register: result
      shell: "docker run --rm --name conteneur_app formation/java:1.0"
    - 
      debug: var=result

